language: python
python:
  - '3.5'
install:
  - echo "Skip install"
script:
  - echo "No tests yet"
addons:
  ssh_known_hosts:
    - "$STAGING_SERVER"
before_script:
  - echo -e "Host $STAGING_SERVER\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
before_deploy:
  - openssl aes-256-cbc -K $encrypted_6d56777c9634_key -iv $encrypted_6d56777c9634_iv -in deployment/deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
  - cat /tmp/deploy_rsa
deploy:
  - provider: script
    skip_cleanup: true
    script: deployment/deploy.sh
    on:
      branch: travis-ci
