language: python
python:
- '3.5'
install:
- pip install -r requirements.txt
script:
- echo "No tests yet"

addons:
  ssh_known_hosts:
  - $STAGING_SERVER

before_script:
  - echo -e "Host $STAGING_SERVERntStrictHostKeyChecking non" >> ~/.ssh/config

script:
  -
before_deploy:
  - openssl aes-256-cbc -K $ENCRYPTED_KEY -iv $ENCRYPTED_IV -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  - provider: script
    skip_cleanup: true
    script: /deploy.sh
    on:
      branch: travis-ci  # master