"""add raw_data to milestone

Revision ID: 7d2634414a30
Revises: f96fb429d728
Create Date: 2018-04-02 02:48:33.485812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d2634414a30'
down_revision = 'f96fb429d728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestone', sa.Column('raw_data', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('milestone', 'raw_data')
    # ### end Alembic commands ###
