"""add number(primary key in github view) to milestone

Revision ID: f96fb429d728
Revises: 2cd0988b9a7b
Create Date: 2018-03-28 21:57:16.560086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f96fb429d728'
down_revision = '2cd0988b9a7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestone', sa.Column('number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('milestone', 'number')
    # ### end Alembic commands ###
